name = "stm32g4_hal"
description = "stm32 : devices, drivers, svd"
version = "0.1.0"
licenses = "BSD-3-Clause"

authors = ["AdaCore"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
website="https://github.com/GNAT-Academic-Program/stm32_hal"
tags = ["embedded", "stm32", "devices", "drivers", "svd"]

[[depends-on]]
cortex_m = "0.5.0"
light_tasking_stm32g431 = "*"

[configuration]
auto_gpr_with = true
disabled = false
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[configuration.variables]
[configuration.variables.device]
default = "stm32g431xx"
type = "Enum"
values = [
    "stm32g431xx",
]

[configuration.values]
cortex_m.core = "m4f"

[[pins]]
hal = { url="https://github.com/Fabien-Chouteau/hal.git", branch="release/0.4" }

[origin]
commit = "30ddf3b15679c81105749c39f9e245b52350252e"
url = "git+https://github.com/evolutek/stm32g4_hal.git"