name = "pa1616d"
description = "pa1616d driver"
version = "0.1.0"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embaded", "stm32", "stellahal", "evolutek"]

[[depends-on]]
gnat_arm_elf = ">=12"
uart = "0.1.0"

[origin]
commit = "585dd4ac80f5d9745e61bd1996267b6d09a0d87a"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "pa1616d"
