name = "uart"
description = "UART driver"
version = "0.1.0"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[configuration.variables]
[configuration.variables.device]
default = "stm32_f4"
type = "Enum"
values = [
    "stm32_f4",
    "stm32_g4",
]

[[depends-on]]
gnat_arm_elf = ">=12"

[origin]
commit = "260b7a7f4971807a3b9d76e5073d28afe422e47f"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "uart"
