name = "as5600"
description = "as5600 driver for stm32f407"
version = "0.1.0-dev"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[[depends-on]]
gnat_arm_elf = "^12"

[origin]
commit = "59bae7d7383ab9c093f68b70b0f05d7dfbb02464"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "as5600"