name = "bmp390"
description = "bmp390 driver for stm32f407"
version = "0.1.0"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[[depends-on]]
gnat_arm_elf = "^12"
stm32f4xxm_devebox = "0.1.0"

[origin]
commit = "d855d8db53ec911c7858d09084d391c4c85930a3"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "bmp390"
