name = "lora"
description = "lora driver"
version = "0.1.0"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[[depends-on]]
gnat_arm_elf = "^12"
hal = "0.4.0"

[origin]
commit = "3fc4d126e675362aa303aebb82610cf0c2dd19f0"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "lora"
